<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\Tenant\AdmissionTestAttempt;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

/**
 * Temporary exam login for admission applicants.
 *
 * On exam day the student visits /exam-login, enters the username +
 * password generated by the school admin, and is redirected to their
 * test page. No persistent session is created — the token URL carries
 * all the state needed by the test controller.
 *
 * Window enforcement (opens_at / closes_at) is checked here so the
 * student gets a friendly error rather than a blank token page.
 */
class ExamLoginController extends Controller
{
    protected function ensureTenant(Request $request): ?\App\Models\Tenant
    {
        if (tenancy()->initialized) {
            return tenant();
        }

        // Try, in priority order:
        //   1. POST body / query string (`tenant=...`)
        //   2. Session (`tenant_id`) — set by the central middleware
        //   3. The HTTP Referer URL's `?tenant=` query (for cases where the
        //      hidden form field never made it but the page was reached via
        //      the email link).
        $hint = $request->input('tenant');

        if (! $hint && $request->hasSession()) {
            $hint = $request->session()->get('tenant_id');
        }

        if (! $hint) {
            $referer = $request->headers->get('referer');
            if ($referer) {
                $query = parse_url($referer, PHP_URL_QUERY) ?: '';
                parse_str($query, $parts);
                $hint = $parts['tenant'] ?? null;
            }
        }

        if (! $hint) {
            \Illuminate\Support\Facades\Log::warning('ExamLogin: tenant could not be resolved', [
                'method'  => $request->method(),
                'host'    => $request->getHost(),
                'path'    => $request->path(),
                'referer' => $request->headers->get('referer'),
                'has_post_tenant' => $request->has('tenant'),
            ]);
            return null;
        }

        $tenant = \App\Models\Tenant::find($hint);
        if (! $tenant) {
            \Illuminate\Support\Facades\Log::warning('ExamLogin: tenant lookup failed', ['hint' => $hint]);
            return null;
        }
        tenancy()->initialize($tenant);
        return $tenant;
    }

    public function show(Request $request)
    {
        $tenant = $this->ensureTenant($request);

        return view('public.exam-login', [
            'tenant'   => $tenant,
            'tenantId' => $tenant?->id ?? $request->input('tenant'),
        ]);
    }

    public function login(Request $request)
    {
        $tenant = $this->ensureTenant($request);

        if (! $tenant) {
            return back()->withErrors([
                'username' => 'School not found. Please open this page from your school\'s URL.',
            ])->withInput($request->only('username'));
        }

        $request->validate([
            'username' => ['required', 'string'],
            'password' => ['required', 'string'],
        ]);

        $fail = fn () => back()->withErrors([
            'username' => 'Invalid username or password.',
        ])->withInput($request->only('username'));

        try {
            $attempt = AdmissionTestAttempt::with(['test'])
                ->where('temp_username', $request->input('username'))
                ->first();
        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error('ExamLogin DB error', ['error' => $e->getMessage()]);
            return back()->withErrors([
                'username' => 'A server error occurred. Please try again or contact the school.',
            ])->withInput($request->only('username'));
        }

        if (! $attempt) {
            return $fail();
        }

        if (! $attempt->temp_password_hash || ! Hash::check($request->input('password'), $attempt->temp_password_hash)) {
            return $fail();
        }

        // Check exam window.
        $test = $attempt->test;

        if ($test && $test->window_opens_at && now()->lessThan($test->window_opens_at)) {
            return back()->withErrors([
                'username' => 'The exam has not opened yet. Access opens at ' . $test->window_opens_at->format('d M Y, H:i') . '.',
            ])->withInput($request->only('username'));
        }

        if ($test && $test->window_closes_at && now()->greaterThan($test->window_closes_at)) {
            return back()->withErrors([
                'username' => 'The exam window has closed. Please contact the school.',
            ])->withInput($request->only('username'));
        }

        if ($attempt->isProctoringCancelled()) {
            return back()->withErrors([
                'username' => 'Your exam was cancelled due to a proctoring violation. Please contact the school.',
            ])->withInput($request->only('username'));
        }

        // All good — go to waiting room first. Preserve the tenant hint
        // in the URL so the post-redirect request can resolve tenancy on
        // the central host where middleware doesn't auto-initialize.
        return redirect()->to(
            route('public.admission-test.waiting', ['token' => $attempt->attempt_token])
            . '?tenant=' . urlencode($tenant->id)
        );
    }
}
